version: '3.8'

services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - drift-ride-service
      - drift-ingestion-service

  drift-ingestion-service:
    build:
      context: ./drift-ingestion-service
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    # Remove exposed ports as Caddy will handle external access
    depends_on:
      - redis

  drift-ride-service:
    build:
      context: ./drift-ride-service
      dockerfile: Dockerfile
    # Remove exposed ports as Caddy will handle external access
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  caddy_data:
  caddy_config: