version: '3.8'

services:
  # caddy:
  #   image: caddy:2-alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #     - caddy_data:/data
  #     - caddy_config:/config
  #   depends_on:
  #     - drift-ride-service
  #     - drift-ingestion-service

  drift-ingestion-service:
    build:
      context: ./drift-ingestion-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=debug
      - ACCESS_LOG=true
    depends_on:
      - redis
    volumes:
      - ./drift-ingestion-service/app:/app/app
      - ./drift-ingestion-service/main.py:/app/main.py
      - ./drift-ingestion-service:/app

  drift-ride-service:
    build:
      context: ./drift-ride-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DRIFT_TESTING_API_KEY=d32aef51-17da-4650-9b08-433b3c5d911e
      - API_KEY=d32aef51-17da-4650-9b08-433b3c5d911e
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=debug
      - ACCESS_LOG=true
    depends_on:
      - redis
    volumes:
      - ./drift-ride-service/app:/app/app
      - ./drift-ride-service/main.py:/app/main.py
      - ./drift-ride-service:/app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

# volumes:
#   caddy_data:
#   caddy_config: